# proj_name: name of the ansible workspace (e.g., example_aws)
# robot_name: machine name (folder name within the "machines" directory)
# username: username on the machine (e.g., "pi")
---
- fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - proj_name
    - robot_name
    - username


- name: Set project variables
  set_fact:
    proj_src_dir: '../machines/{{ robot_name }}/'
    proj_dest_dir: '/home/{{ username }}/{{ proj_name }}/'

