---
# ansible-playbook -i inventories/twins_office --extra-vars "target=twins_drones username=pi" playbooks/shutdown.yml -K
- hosts: "{{target}}"
  vars:
    target: "all"
  remote_user: "{{username}}"
  become: yes
  tasks:
    - name: "Shutdown the system "
      command: shutdown -h now
